// IPC Events
module.exports = {
	START_SESSION: 'START_SESSION',
	STOP_SESSION: 'STOP_SESSION',
  LINECHART_SESSION: 'LINECHART_SESSION',
  COP_SESSION: 'COP_SESSION',
  SPEEDMETER_SESSION: 'SPEEDMETER_SESSION',
  TIMELINE_SESSION: 'TIMELINE_SESSION',
  SESSION_OPTIONS: 'SESSION_OPTIONS',
  DEVICE_DETAILS: 'DEVICE_DETAILS',
  RESET_FORCE_PLATES: 'RESET_FORCE_PLATES',
  WINDOWS_STATUS: 'WINDOWS_STATUS',
  WINDOWS_STATUS_RESPONSE: 'WINDOWS_STATUS_RESPONSE',
  CREATE_DATABASE: 'CREATE_DATABASE',
  CREATE_DATABASE_RESPONSE: 'CREATE_DATABASE_RESPONSE',
  DELETE_DATABASE: 'DELETE_DATABASE',
  DELETE_DATABASE_RESPONSE: 'DELETE_DATABASE_RESPONSE'
};
